name: Update nixpkgs
permissions:
  contents: write
on:
  schedule:
    - cron: '* * * * */15'
  push:
    branches:
     - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
    - run: |
        git config --global user.email "redistributable-nix@mkg20001.io"
        git config --global user.name "Bot"
        nix flake update
        if ! git diff-index --quiet HEAD --; then
          git add flake.lock
          git commit -m "update lockfile"
        fi
    - uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
